### ISSUE TITLE
JSON Server in Snow Leopard: illegal instruction

### ISSUE THREAD

**Issue by raulgotor** [johnlauer/serial-port-json-server#15]
Hi John:

After downloading JSON server (v1.77) and running it on OS X 10.6.8, I got a "illegal instruction" response from the terminal. I'm stuck here, do you have some idea of what can be going on??

Thank you in advance

Raúl

**Comment by johnlauer** [comment]
Can you ping Jarret Luft? He compiled the mac version. Not sure if this is mac specific.

**Comment by raulgotor** [comment]
Ok John, thanks!

**Comment by raulgotor** [comment]
Building it from source in Snow Leopard solved this problem. Thanks!
