### ISSUE TITLE
Raspberry PI Serial Port

### ISSUE THREAD

**Issue by azekie** [johnlauer/serial-port-json-server#29]
Hi John,
I have an issue with SPJS, I setup my CNC3040 as the following:
- I installed GRBL on Arduino Pro Mini (which has no USB-to-Serial Connection).
- I connected Rx/Tx pins of Arduino to Tx/Rx pins of Raspberry PI GPIO via logic level shift circuit.
- I disabled Raspberry PI console input/output, so I can use the serial port from SPJS.
- SPJS is installed on the PI.
- I'm using Chilipepper to control my CNC machine through the network.

The setup works great when I start SPJS manually (./serial-port-json-server), SPJS lists the internal serial port of the PI as ttyAMA0, but when I run SPJS as a service it doesn't show that port! any idea how to fix this?

Thanks

Ameen

**Comment by johnlauer** [comment]
That sounds like an awesome setup. Can you post a video for all of us to see how creative you got? I've never heard of anybody doing it quite like this, but it makes sense.

My first guess would be that it's simply a permissions issue if you can do this manually. Have you tried that?

**Comment by azekie** [comment]
I found the solution, the startup script lists only USB serial ports, so I removed -regex usb from the following line:

/home/pi/serial-port-json-server_linux_arm/serial-port-json-server -regex usb &

I'm still experimenting with this setup, I'll post a video or do indestructible when I complete, here is a photo for now.

Regards

Ameen
![imag0291](https://cloud.githubusercontent.com/assets/6442829/10264711/ddb07a52-6a1c-11e5-977c-d45774a71b4e.jpg)
