### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by ylh888** [johnlauer/serial-port-json-server#30]
Great program - what I have been looking for.

I have been successfully used the chilipeppr's hardware fiddle to connect to an Arduino. Send and receive was fine. I then disconnect in chilipeppr and try to use a web socket code to connect. I got the following when I ran the code (below the error message):
```
index2.html:8 WebSocket is supported by your Browser!
index2.html:11 WebSocket connection to 'ws://localhost/ws' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
index2.html:28 Connection is closed...
```

index2.html is simply:
```
<!DOCTYPE HTML>
<html>

<head>
  <script type="text/javascript">
    function WebSocketTest() {
      if ("WebSocket" in window) {
        console.log("WebSocket is supported by your Browser!");

        // Let us open a web socket
        var ws = new WebSocket("ws://localhost/ws");

        ws.onopen = function () {
          // Web Socket is connected, send data using send()
          ws.send("list");
          console.log("sending list");
        };

        ws.onmessage = function (evt) {
          var received_msg = evt.data;
          console.log("Message is received...");
          console.log(evt.data);
        };

        ws.onclose = function () {
          // websocket is closed.
          console.log("Connection is closed...");
        };
      } else {
        // The browser doesn't support WebSocket
        console.log("WebSocket NOT supported by your Browser!");
      }
    }
  </script>
</head>

<body>

  <div id="sse">
    <a href="javascript:WebSocketTest()">Run WebSocket</a>
  </div>
</body>

</html>
```

**Comment by johnlauer** [comment]
From scanning through your code it looks fine, so not sure. Are you sure your SPJS is running before you execute this Javascript?

**Comment by ylh888** [comment]
SPJS is definitely running as I have been able to communicate to the serial port using the Chilipeppr  hardware fiddle. I was careful to disconnect in that app first before testing the above html code. I have tested this using two separate machines, an iMac (mid 2009) and an Macbook Air (2011) both running El Capitan.

Curiously, although both machines exhibited identical behaviour. 'ps" shows the SPJS running on the iMac but not MBA (even though I could connect to it!)

Is there anything else I could try?

**Comment by johnlauer** [comment]
Spjs allows unlimited parallel connections. So you don't have to disconnect. I would look at my JavaScript code in jsFiddle for the serial port widget to make sure that your code logic is correct.



On Sun, Nov 29, 2015 at 9:46 AM -0800, "ylh888" <notifications@github.com<mailto:notifications@github.com>> wrote:


SPJS is definitely running as I have been able to communicate to the serial port using the Chilipeppr hardware fiddle. I was careful to disconnect in that app first before testing the above html code. I have tested this using two separate machines, an iMac (mid 2009) and an Macbook Air (2011) both running El Capitan.

Curiously, although both machines exhibited identical behaviour. 'ps" shows the SPJS running on the iMac but not MBA (even though I could connect to it!)

Is there anything else I could try?

-

**Comment by ylh888** [comment]
the answer is that the socket is at "ws://localhost:8989/ws".

Thanks for your help. Please change the README file.

**Comment by ylh888** [comment]
As you see, I found the problem. 

It is still curious (to me at least) that the JSPS service does not show up in ‘ps’ even though it is running.

how does one stop it then?

**Comment by johnlauer** [comment]
I always see it in ps and I tend to do a killall or I set up an etc/init.d. You can also say exit from the console of the serial port widget cuz it supports that command



On Sun, Nov 29, 2015 at 12:48 PM -0800, "ylh888" <notifications@github.com<mailto:notifications@github.com>> wrote:

As you see, I found the problem.

It is still curious (to me at least) that the JSPS service does not show up in 'ps' even though it is running.

how does one stop it then?

> On Nov 29, 2015, at 12:55 PM, John Lauer <notifications@github.com> wrote:
>
> Spjs allows unlimited parallel connections. So you don't have to disconnect. I would look at my JavaScript code in jsFiddle for the serial port widget to make sure that your code logic is correct.
>
>
>
> On Sun, Nov 29, 2015 at 9:46 AM -0800, "ylh888" <notifications@github.com<mailto:notifications@github.com>> wrote:
>
>
> SPJS is definitely running as I have been able to communicate to the serial port using the Chilipeppr hardware fiddle. I was careful to disconnect in that app first before testing the above html code. I have tested this using two separate machines, an iMac (mid 2009) and an Macbook Air (2011) both running El Capitan.
>
> Curiously, although both machines exhibited identical behaviour. 'ps" shows the SPJS running on the iMac but not MBA (even though I could connect to it!)
>
> Is there anything else I could try?
>
> -
> Reply to this email directly or view it on GitHub<https://github.com/johnlauer/serial-port-json-server/issues/30#issuecomment-160436942>.
> -
> Reply to this email directly or view it on GitHub <https://github.com/johnlauer/serial-port-json-server/issues/30#issuecomment-160440011>.
>


-
