### ISSUE TITLE
programfromurl ends with "Could not program the board" at my odroid u3

### ISSUE THREAD

**Issue by Fips11** [johnlauer/serial-port-json-server#34]
if I'm using an operating system with the arduino ide at the port /dev/ttyACM99 it all works perfect.
but when I'm using my server system with spjs at port /dev/ttySAC0 , the same hex file and at the same Hardware, I'm getting this message. 
the send command works fine at this port. 

Dose anyone have an idea why its like that?

**Comment by johnlauer** [comment]
What operating system are you running in both scenarios? What type of board are you programming? Is it AVR based or Bossac based? I’ve never even heard of a device running on ttySAC0 so what is that?

**Comment by Fips11** [comment]
It's a  Arduino Uno compatible I/O-board. ttySAC0 is the UART between Server-board and IO-board. both systems are Ubuntu 14.04 LTS. 
   
Ok I have found the problem. the IDE triggers the resetpin of the controllerboard by a gpio pin of my server.   if I edit your code and add 2-3 commands it should solve the problem. 

if I type 
echo 204 > /sys/class/gpio/export 
echo out > /sys/class/gpio/gpio204/direction
echo 1 > /sys/class/gpio/gpio204/value
echo 0 > /sys/class/gpio/gpio204/value

and run avrdude. All perfekt.
