### ISSUE TITLE
How to uninstall

### ISSUE THREAD

**Issue by cojarbi** [johnlauer/serial-port-json-server#36]
For some reason its generating error conecting to a node.js server im running. How i can remove the install?

**Comment by chilipeppr** [comment]
SPJS doesn't use nodejs so I'm not sure what you're talking about?

**Comment by cojarbi** [comment]
Correct but I'm unable to connect via serial to a node.js server since installing it.  I did shut down json server but still

Ariel Yahni

**Comment by chilipeppr** [comment]
There is no install for spjs. It's just a binary that you run. So if you
kill it you are good to go.

**Comment by cojarbi** [comment]
Thanks John. I will continue my search then

Ariel Yahni

**Comment by TemperedEnterprises** [comment]
@cojarbi ,

It is a copy install. Just delete it from the hard disk and it will be uninstalled.
