### ISSUE TITLE
Init script

### ISSUE THREAD

**Issue by peteruithoven** [johnlauer/serial-port-json-server#5]
I'm running the serial port json server on a Raspberry Pi and I'm autostarting it using the following init script:

```
#! /bin/sh
# /etc/init.d/noip 
/home/pi/serial-port-json-server_linux_arm/serial-port-json-server > /tmp/frees.log 2> /tmp/freeserror.log`
```

I would love to have "proper" start, stop, restart commands handling so it's easier to restart the server. 
Any tips on this?  
Are there any go specific easier solutions? 

How do you guys do this? 
I speak some Bash, but _/etc/init.d/skeleton_ doesn't really help me.

**Comment by johnlauer** [comment]
Here's a really lightweight /etc/init.d that I use on a Raspberry Pi.

#! /bin/sh
### BEGIN INIT INFO
# Provides:          serial-port-json-server
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Manage my cool stuff
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin

. /lib/init/vars.sh
. /lib/lsb/init-functions
# If you need to source some other scripts, do it here

case "$1" in
  start)
    log_begin_msg "Starting Serial Port JSON Server service"
# do something
        /home/pi/serial-port-json-server_linux_arm/serial-port-json-server &
    log_end_msg $?
    exit 0
    ;;
  stop)
    log_begin_msg "Stopping the Serial Port JSON Server"

    # do something to kill the service or cleanup or nothing
    killall serial-port-json-server
    log_end_msg $?
    exit 0
    ;;
  *)
    echo "Usage: /etc/init.d/serial-port-json-server {start|stop}"
    exit 1
    ;;
esac

**Comment by johnlauer** [comment]
Then you need to run the following command to setup your /etc/init.d script

```
sudo update-rc.d serial-port-json-server defaults
```

**Comment by johnlauer** [comment]
And of course to start/stop the service:

```
sudo service serial-port-json-server stop
```
```
sudo service serial-port-json-server start
```
