### ISSUE TITLE
fails to send tinyg2 sr configuration

### ISSUE THREAD

**Issue by stg** [johnlauer/serial-port-json-server#52]
I've had this problem for some time but never got around to diagnosing it.
I am running Windows, and the problem has been verified with different computers.

Symptoms first found with chilipeppr:
¤1 I'm not able to use the "Set Gxx zero" button.
¤2 When I connect, I always end up with one message left in the spjs queue that has to be % flushed.

The reason for ¤1 is that status reports never get configured to provide "mpox" thru "mopa".
The reason for this is in turn that the {"sr":{"field":t,...}} command never gets sent to the serial port, but instead gets stuck in the queue and also happens to be the cause of symptom ¤1.
Trying to manually send the command results in the same behavior.

Further testing reveals that it is possible to issue this command, but with some form of length restriction.

This command works just fine:

sendjson {"P":"COM4","Data":[{"D":"{\"sr\":{\"line\":t,\"posx\":t,\"posy\":t,\"posz\":t,\"vel\":t,\"unit\":t,\"stat\":t,\"feed\":t,\"coor\":t}}\n","Id":"works"}]}

However, this command with two more json terms - locks up the buffers:

sendjson {"P":"COM4","Data":[{"D":"{\"sr\":{\"line\":t,\"posx\":t,\"posy\":t,\"posz\":t,\"vel\":t,\"unit\":t,\"stat\":t,\"feed\":t,\"coor\":t,\"momo\":t,\"plan\":t}}\n","Id":"killsthequeue"}]}

I have verified with a serial port monitor that the command does not, in fact, get sent.

**Comment by johnlauer** [comment]
This wouldn’t be a serial port json server issue. This is a ChiliPeppr issue and it seems you are using TinyG G2 which has a special “send no init cmds” mode you should turn on in ChiliPeppr TinyG workspace. It’s in the upper right corner triangle menu of the TinyG widget.

**Comment by stg** [comment]
Your answer confuses me.

We can leave chilipeppr out of the equation, I am WebSocket'ing to SPJS from other applications as well and I have the same problem.

I am asking SPJS to send a command, but it is never sent and instead causes further issues. I would like to know why that is so that I can avoid this issue in my own application.

When things go wrong, SPJS in verbose mode reports "It looks like the buffer is over the allowed size, so we are going to pause.". The buffer is 107 bytes. If this is by design or imposed by TinyG2, where can I find more information?

**Comment by chilipeppr** [comment]
Well, your error then is you are sending a command too long for TinyG G2. I
don't think anything in your description is a problem with SPJS. It's just
that you are sending data too long and possibly not initializing G2
correctly to get back status reports. Just mimic how ChiliPeppr does it in
"send no init cmds" mode.

**Comment by stg** [comment]
Ok, so digging through the SPJS code I found that there is a 100 byte limit hard-coded into bufferflow_tinygg2.go. I suppose this originates in a limitation defined by G2?

Anyways, with chilipeppr in "send no init cmds" mode, there is no attempt to configure the status report at all, leaving it at the default - or whatever the last application asked for. Seems pretty broken, but has nothing to do with SPJS...

Case closed?

**Comment by chilipeppr** [comment]
That 100 byte limit is defined by G2, not ChiliPeppr or SPJS. G2 runs in
line mode which maxes on line size. As far as i recall there is a small sr
report request sent in "send no init cmds" mode. Also CP lets you define
settings to send on connect for your specific G2 device in case you don't
have your stepper settings compiled in your firmware. those settings are
defined in the cog wheel icon per serial device in the spjs widget in lower
right corner in CP.

**Comment by stg** [comment]
I know, I know. I've used those features frequently.

The problem is that chilipeppr requires more sr fields than the maximum line length allows one to configure. TinyG has an incremental configuration which would solve this by splitting into multiple commands, but this seems yet to make it into G2. For now it seems all fields must be sent in one message which requires more than 100 chars.

**Comment by johnlauer** [comment]
That’s why ChiliPeppr has “send no init cmds” mode

**Comment by stg** [comment]
I implemented incremental set status report fields and modified my application and chilipeppr startup scripts accordingly. Everything works fine.

I am sorry that I mistakenly thought the message getting "stuck" in SPJS was a fault with SPJS.
Thank you for your insight.
