### ISSUE TITLE
fatal error: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by lutorm** [johnlauer/serial-port-json-server#55]
I'm getting this constantly trying to run chilipeppr from my new Macbook Pro. The same thing happens with the old one I've used successfully for a long time on my old Macbook Air and the new 1.86 that I just downloaded. It will run a job for only a minute or two before dying. Any ideas?

[error.txt](https://github.com/johnlauer/serial-port-json-server/files/574229/error.txt)

**Comment by chilipeppr** [comment]
Use the latest Mac build in github release

**Comment by lutorm** [comment]
Yeah I realized there are two serial-port-json-server projects and found the other one. (If this one isn't used maybe it can be marked somehow?) Works perfectly now, thanks.

**Comment by chilipeppr** [comment]
Well, the homepage is marked with a big font saying the repo was moved.

**Comment by lutorm** [comment]
Oh. Google didn't take me there :)
