### ISSUE TITLE
Arch Linux: No serial ports found

### ISSUE THREAD

**Issue by bastian-f** [johnlauer/serial-port-json-server#64]
Hello,

When I execute serial-port-json-server in Arch Linux on my laptop with both Arch Linux and Win8 installed I only get the message "No serial ports found" while in windows it finds the serial port.

I tried  to find documentation or if somebody had the same problem but I couldn't find anything.

What could be the problem? Thank you!

**Comment by johnlauer** [comment]
You probably don’t have usb drivers working that detect your device and create your serial port. SPJS just gets it’s list from the OS, so the OS doesn’t have a list.

**Comment by bastian-f** [comment]
I just figured it out, I had to load the module cdc_amc.

**Comment by bastian-f** [comment]
Sorry, I mistyped. The module is called cdc_acm.
