### ISSUE TITLE
Local communication without internet

### ISSUE THREAD

**Issue by ShabrawyPrime** [johnlauer/serial-port-json-server#66]
So Serial port json server works fine and even runs from raspberry pi and everything is okay.
Except I need to use an offline GUI as the internet signal isn't great at that end of the work shop and using an interface other than any online thing is the purpose. How can I make an interface like UGS or BCNC read the web socket or maybe even connect to repetier host some app with local network connection ability ?

**Comment by chilipeppr** [comment]
Spjs only works with chilipeppr

**Comment by ShabrawyPrime** [comment]
Thanks for the fast answer
