### ISSUE TITLE
 Missing tls cert and/or key. Will not start HTTPS server.

### ISSUE THREAD

**Issue by pastprimitive** [johnlauer/serial-port-json-server#76]
When I start SPJS v1.96 on OS X Catalina I get the following error message: 

 "Missing tls cert and/or key. Will not start HTTPS server."

I need it to run via https to connect to an app that runs inside of Onshape. But am unsure of what I need to do to generate the tls cert and/or key. If anyone could give me some guidance or point me in the right direction it would be much appreciated. 

Thank you so much.

**Comment by chilipeppr** [comment]
This repo is deprecated. You should be using https://github.com/chilipeppr/serial-port-json-server

**Comment by pastprimitive** [comment]
Just realized I got the repos mixed up. I'll close this out and move it there. Thanks.
